---
language: python
python:
  - "3.9"
services: docker
dist: focal

env:
  matrix:
    - MOLECULE_DISTRO: ubuntu2004
    - MOLECULE_DISTRO: debian11
    - MOLECULE_DISTRO: rockylinux8

install:
  - pip install ansible docker molecule-docker

script:
  - molecule test

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
